### ISSUE TITLE
Site load time on mobile

### ISSUE THREAD

**Issue by dennissherman** [midrealm/mk-peerage#29]
I'm viewing the site on a mobile device ( Google pixel) on a WiFi network, and the initial load is painfully slow. I didn't time it, felt like 8+ seconds

**Comment by niquerio** [comment]
This might be a problem with Heroku. After an hour the site goes to sleep. The dyno has to wake up when a new user looks at the site: https://blog.heroku.com/app_sleeping_on_heroku

**Comment by dennissherman** [comment]
I'll look again in a couple weeks. We're on vacation right now with spotty and slow internet. Cruise ships _are_ mobile devices... Currently between Spain and Morocco, passing Gibraltar after dinner tonight. 

Dennis Sherman
Chicago, IL
http://www.dennissherman.com 
 
  On Sun, Mar 25, 2018 at 7:15 PM, Monique Rio<notifications@github.com> wrote:   
This might be a problem with Heroku. After an hour the site goes to sleep. The dyno has to wake up when a new user looks at the site: https://blog.heroku.com/app_sleeping_on_heroku

**Comment by niquerio** [comment]
Sounds nice! Hope you are having fun! :)

**Comment by niquerio** [comment]
Shouldn't be an issue now.
